name: Laravel CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, pdo, pdo_mysql, openssl, tokenizer, xml, ctype, json
          coverage: none

      - name: verify php version
        run: php -v

      - name: install composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: build frontend assets
        run: |
          npm ci
          npm run build

      - name: deplot to azure vm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 2121
          script: |
            set -e

            cd /var/www/fairsky

            echo "pphp version"
            php -v

            echo "ensure php 8.4"
            sudo update-alternatives --set php /usr/bin/php8.4

            echo "php version after switch"
            php -v

            echo "reset broken vendor"
            rm -rf vendor
            git checkout -- composer-lock

            echo "install dependencies with php 8.4"
            php8.4 /usr/local/bin/composer install --no-dev --optimizer-autoloader --no-interaction --prefer-dist

            echo "run migration"
            php8.4 artisan migrate --force

            echo "optimize laravel"
            php8.4 artisan optimize
            php8.4 artisan config:clear
            php8.4 artisan route:clear
            php8.4 artisan view:clear

            echo "reload php-fpm"
            sudo systemctl reload php8.4-fpm
